# AetherLink System Configuration

system:
  controller_name: "Jetson-AGX-Orin"
  enable_ui: true
  enable_sdr: true
  use_box_scan: true
  soft_limit_offset_deg: 2.0

serial_ports:
  gps: "/dev/ttyUSB0"
  imu: "/dev/ttyUSB1"
  azimuth_motor: "/dev/ttyUSB2"
  elevation_motor: "/dev/ttyUSB3"
  pan_motor: "/dev/ttyUSB4"

motor_settings:
  azimuth:
    stall_detection_enabled: true
    soft_limit_enabled: true
    max_degrees: 700
  elevation:
    stall_detection_enabled: true
    soft_limit_enabled: true
    max_degrees: 180
  pan:
    stall_detection_enabled: true
    soft_limit_enabled: true
    max_degrees: 30

sdr:
  beacon_scan_band: "SHF"
  default_frequency_mhz: 10750
  box_scan_step_deg: 0.2
  box_scan_range_deg: 2.0

ui:
  listen_ip: "0.0.0.0"
  port: 8000
  show_horizon_map: true
